### ISSUE TITLE
Add schema property to schematics providing CLI hints and Angular Console support

### ISSUE THREAD

**Issue by adammedford** [ngxs/schematics#14]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
The provided schematics do not have a 'schema' property referencing a schema.json for each schematic.
Just schema.d.ts which provides typing but emits no usable code.

## Expected behavior
Each schematic has a schema property populated with the path to a JSON file providing schematic defaults. 

## What is the motivation / use case for changing the behavior?
Required for use with Angular Console and prompts provided by the CLI; can be used for additional schematic validation internally

**Comment by markwhitfeld** [comment]
Thank you! @adammedford any guidance available to on what this looks like?

**Comment by adammedford** [comment]
> Thank you! @adammedford any guidance available to on what this looks like?

I could submit a PR if you're open to it

**Comment by markwhitfeld** [comment]
That would be amazing! Thank you

**Comment by markwhitfeld** [comment]
PR has been merged. Will do a release soon.

**Comment by markwhitfeld** [comment]
These changes have been released and the new version is working in Angular Console.

**Comment by adammedford** [comment]
Adding @ngxs/schematics to the Angular Console extensions list so it will be visible as an installable schematic library

https://github.com/nrwl/angular-console/issues/204
https://github.com/nrwl/angular-console/pull/438
