### ISSUE TITLE
ng add @ngxs/store

### ISSUE THREAD

**Issue by splincode** [ngxs/schematics#4]
```
ng add @ngxs/store
```

**Comment by kyusupov33** [comment]
Using the command `ng add @ngxs/schematics` you will add to your project:
- @ngxs/schematics
- @ngxs/store
- @ngxs/logger
- @ngxs/devtools

They will all be added in `dependency`.

P.S. angular/cli command `ng add` provides the ability to add a package to `devDependency` with --no-save option, but for some reason it is not completed. 

Now the default flag is `true`
```ts
save = true
```
I will try to make PR and fix the bug in the main repository, then it will be possible to add a package @ngxs/schematics in `devDependency`
