### ISSUE TITLE
ng add adds 1.0.0 of @ngxs/schematics to package, which doesn't exist

### ISSUE THREAD

**Issue by kayvanbree** [ngxs/schematics#8]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
When running `ng add @ngxs/schematics`, Angular tries to add `1.0.0` to the package.json. Since the `0.0.1-alpha.0` was just released, that doesn't make any sense.

For a workaround: Just change the package.json version to `0.0.1-alpha.0`. 

## Expected behavior
I would expect the command to install the latest version. 

## Minimal reproduction of the problem with instructions

Run `ng add @ngxs/schematics`

## What is the motivation / use case for changing the behavior?
It seems a waste of time and prone to errors to have to define your ngxs/schematics version before every release.

**Comment by markwhitfeld** [comment]
Thanks for the report! The joys of an alpha version.
If you would like to contribute a PR to fix this we would be very happy! 👍

**Comment by kayvanbree** [comment]
I'd like that, but I won't like manually editing the version. Maybe it should be done automatically?

**Comment by eranshmil** [comment]
@kayvanbree @markwhitfeld 
Fixed in PR #9.

**Comment by kayvanbree** [comment]
@eranshmil Awesome! I was gonna do this way more difficult!

**Comment by eranshmil** [comment]
@markwhitfeld @splincode 
Please close this issue.
